### ISSUE TITLE
random.randint now synchronised 

### ISSUE THREAD

**Issue by shivangdubey** [shivangdubey/HacktoberFest2020#10]
After choosing options other than A, it still guesses between 10-20 (range option of A). I assume there is some calling error.

**Comment by divya144** [comment]
@shivangdubey  I would like to work on this issue.

**Comment by Icelain** [comment]
The only possible cause I can think of is random.randint() considering the stop parameter when executing. We can either use random.randrange() or decrease the stop parameter by 1.

**Comment by shivangdubey** [comment]
> The only possible cause I can think of is random.randint() considering the stop parameter(21,31,41 etc) when executing. We can either use random.randrange() or decrease the stop parameter by 1.

It is resolved, by the way your method might be correct. Decreasing the parameter by 1 won't be helpful enough.
