### ISSUE TITLE
Cpp appear two times!?

### ISSUE THREAD

**Issue by sukhchain99** [shivangdubey/HacktoberFest2020#102]
Why are there two c++ sections under Languages Used in main Readme.md file?

**Comment by Pratikzzz** [comment]
Donno but easy fix!

**Comment by shivangdubey** [comment]
Exactly, waiting for someone to fix it.

**Comment by Pratikzzz** [comment]
Can I do that?

**Comment by shivangdubey** [comment]
Yes.

> Can I do that?
