### ISSUE TITLE
Add readme file to every program.

### ISSUE THREAD

**Issue by seema1711** [shivangdubey/HacktoberFest2020#120]
While going through this project, I found that most of the programs don't have any readme file, so it would be difficult for the newcomers to understand the code.

**Comment by shivangdubey** [comment]
Right, we should get separate Readme.md for each project. Anyone willing to contribute will get assigned.

**Comment by ShraddhaDevaiya** [comment]
Hi, can you please assign this task to me ? @shivangdubey

**Comment by StriverFive** [comment]
Hi, i'd like to contribute to this. Can i?

**Comment by shivangdubey** [comment]
> Hi, i'd like to contribute to this. Can i?

Sure.

**Comment by ghanender-chauhan** [comment]
i would like to contribute on this?? can I

**Comment by shivangdubey** [comment]
> i would like to contribute on this?? can I

If you have anything relevant, then sure!

**Comment by samriddhisv** [comment]
Hey, I would love to contribute to this.

**Comment by UtkarshPrakash** [comment]
Hello, I would also like to contribute to this.

**Comment by shivangdubey** [comment]
> Hello, I would also like to contribute to this.

Sure, hope to see some interesting contributions.
