### ISSUE TITLE
Editing the Repository's Readme

### ISSUE THREAD

**Issue by shivangdubey** [shivangdubey/HacktoberFest2020#122]
I am looking for a repo focused readme file and not a general readme. Also add a big, bold statement to **DESCRIBE ABOUT THE PR BEING PULLED**; the description part is not meant to be leave blank.

**Comment by atulbhatt-system32** [comment]
I would like to work on this issue :)

**Comment by comrade-om** [comment]
Are you asking to put in a CONTRIBUTING.md file and steps to create issues and pull requests in the README.md file @shivangdubey ?

**Comment by thepurpleowl** [comment]
I would like to work on this. You can assign it to me.

**Comment by shivangdubey** [comment]
> Are you asking to put in a CONTRIBUTING.md file and steps to create issues and pull requests in the README.md file @shivangdubey ?

To some extend, but I am more focused on how to *Present a PR* basically. Usually we get PRs with no description and  no readme, so it gets difficult to understand what the contributor wants to contribute in the repository.

**Comment by shivangdubey** [comment]
@thepurpleowl Don't include files from your repository (forked repo). Add the .md file in the same repository (the parent repo) and pull a request again.

**Comment by thepurpleowl** [comment]
@shivangdubey I think what you are telling is achieved in this PR. We have a Contributing.md at parent dir. Please rectify me if I am misunderstanding the requirement.
