### ISSUE TITLE
Need more maintainers.

### ISSUE THREAD

**Issue by jaskirat2k** [shivangdubey/HacktoberFest2020#212]
I think this repository has outgrown it's original purpose. I think now it needs more maintainers, although it's my personal opinion, just a suggestion.

**Comment by shivangdubey** [comment]
> I think this repository has outgrown it's original purpose. I think now it needs more maintainers, although it's my personal opinion, just a suggestion.

The purpose was to let contributors to contribute in Open Source being newcomers and to enhance the already existing codes and documentation, if that isn't being fulfilled let me know.
