### ISSUE TITLE
While cloning this repository people are getting this error.

### ISSUE THREAD

**Issue by seema1711** [shivangdubey/HacktoberFest2020#285]
![image](https://user-images.githubusercontent.com/48756444/95981659-9ffe4580-0e3c-11eb-9ce8-333830675e30.png)

**Comment by shivangdubey** [comment]
Thank you for highlighting this, will get this resolved asap.

**Comment by shivangdubey** [comment]
It's rectified, now the contributors won't find problem in cloning. Thank you
