### ISSUE TITLE
Making Guess Game efficient

### ISSUE THREAD

**Issue by shivangdubey** [shivangdubey/HacktoberFest2020#31]
Any ideas for making Guess Game more faster and efficient? Also any interface changes are welcome.

**Comment by Icelain** [comment]
What about using colorama to make a colorful interface?

**Comment by shivangdubey** [comment]
> What about using colorama to make a colorful interface?

Nice. Go for it. 
Also try something to improve the game efficiency and adding more features.

**Comment by Paritosh1007** [comment]
should I make a hard, medium and easy  mode for the game.

Hard mode : regenerates the number after each try as it becomes easy to guess after 2 try.
medium mode : regenerates the number after 2 try. 
easy mode :- same as game in current state.

**Comment by shivangdubey** [comment]
> should I make a hard, medium and easy mode for the game.
> 
> Hard mode : regenerates the number after each try as it becomes easy to guess after 2 try.
> medium mode : regenerates the number after 2 try.
> easy mode :- same as game in current state.

That seems interesting, go for a leveled game.

**Comment by zeeshanok** [comment]
How about showing a number line of the range of numbers and every time the user guesses it will add a point to the number line?
For example:
```
|>----------------------------------------------------------------------------<|
10                                                                            20
```

**Comment by Icelain** [comment]
![Uploading screenshot.png…]()
How does this look like?

**Comment by Icelain** [comment]
How does think look like?
![screenshot](https://user-images.githubusercontent.com/50962640/94779147-171aef00-03e4-11eb-95cf-6ebb0ced5f33.jpg)

**Comment by shivangdubey** [comment]
> How does this look like?
> ![screenshot](https://user-images.githubusercontent.com/50962640/94779147-171aef00-03e4-11eb-95cf-6ebb0ced5f33.jpg)

Creative!

**Comment by shivangdubey** [comment]
> > How does this look like?
> > ![screenshot](https://user-images.githubusercontent.com/50962640/94779147-171aef00-03e4-11eb-95cf-6ebb0ced5f33.jpg)
> 
> Creative!

Can you try doing this in Jupyter Notebook ?

**Comment by shivangdubey** [comment]
> How about showing a number line of the range of numbers and every time the user guesses it will add a point to the number line?
> For example:
> 
> ```
> |>----------------------------------------------------------------------------<|
> 10                                                                            20
> ```

This won't add a valuable contribution. It's just formatting, we would like to increase the working efficiency first.

**Comment by zeeshanok** [comment]
> > How about showing a number line of the range of numbers and every time the user guesses it will add a point to the number line?
> > For example:
> > ```
> > |>----------------------------------------------------------------------------<|
> > 10                                                                            20
> > ```
> 
> This won't add a valuable contribution. It's just formatting, we would like to increase the working efficiency first.

Ok, I was just suggesting. Sorry for the inconvenience.

**Comment by Paritosh1007** [comment]
added easy and hard mode to guess_game.py 

![hard and easy](https://user-images.githubusercontent.com/62282114/94802434-4c840480-0405-11eb-8c20-fe49fcada90f.png)

**Comment by zeeshanok** [comment]
What about an option E which lets u choose your own range of numbers? (only in hard and medium mode)

**Comment by shivangdubey** [comment]
> What about an option E which lets u choose your own range of numbers? (only in hard and medium mode)

Not a bad idea. I will assign anyone willing to add "E" option.

**Comment by shivangdubey** [comment]
More updates and enhancements are always welcome.
