### ISSUE TITLE
Documentation and Formatting

### ISSUE THREAD

**Issue by shivangdubey** [shivangdubey/HacktoberFest2020#55]
New scripts have been added which are:
1) Colour Detection (Python3)
2) Die Game (Python3)
3) Largest and Minimum Number Guesser (C++)
4) Health Reminder (Python3)
5) Snake Game (Python3)
6) Dynamic Programming Basics (Java)
These are open for enhancement and formatting. Also update the readme and gitignore.

## Please give a brief of commits you make.

**Comment by anishjain94** [comment]
Added DP Basics With CPP and Updated ReadMe #70

**Comment by anishjain94** [comment]
Conflicts Resolved  - PR #70
